# Generated by Django 4.0.1 on 2022-02-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone',
        ),
    ]
